//export const DERPIES_ADDRESS = process.env.REACT_APP_DERPIES_ADDRESS_RINKEBY; // deployment
// export const DERPIES_ADDRESS = process.env.REACT_APP_DERPIES_ADDRESS_LOCALHOST; // development

export const MYSTERY_BOX_ADDRESS = process.env.REACT_APP_MYSTERY_BOX_ADDRESS_BSCTEST; // BSC Testnet deployment
//export const MYSTERY_BOX_ADDRESS = process.env.REACT_APP_MYSTERY_BOX_ADDRESS_RINKEBY; // Rinkeby deployment
// export const MYSTERY_BOX__ADDRESS = process.env.REACT_APP_MYSTERY_BOX_ADDRESS_LOCALHOST; // development

export const VRFCOORDINATORMOCK_ADDRESS_LOCALHOST = process.env.REACT_APP_VRFCOORDINATORMOCK_ADDRESS_LOCALHOST;

const MINUTES_TO_MILLISECONDS = 60 * 1000;
export const CHAINLINK_WAIT_TIME_MINUTES = 0.5 * MINUTES_TO_MILLISECONDS;
